data_transforms:
  input_size: 224

trainer:
  n_step_f: 4 # MCD N_STEP_F
  batch_size: 128
#  max_epochs: 200
  num_workers: 4
  save_model_addr: 'checkpoints/C2S'
  forget_rate: 0.5

optimizer:
  name: 'SGD'
  params:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005

data:
  type: 'pacs'
  class_number: 7
  root: 'data/pacs'
  webroot: 'data/web_pacs'
  source_domain_x: 'cartoon'
  source_domain_u_1: 'art_painting'
  source_domain_u_2: 'photo'
  target_domain: 'sketch'

log:
  save_addr: 'log'
  save_name: 'UDAG_C2S'

ratio: 0.4 # a ratio to split samples into clean set and noisy set
