data_transforms:
  input_size: 224

trainer:
  n_step_f: 4 # MCD N_STEP_F
  batch_size: 128
#  max_epochs: 200
  num_workers: 4
  save_model_addr: 'checkpoints/product2clipart'
  forget_rate: 0.5

optimizer:
  name: 'SGD'
  params:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005

data:
  type: 'officeHome'
  class_number: 65
  root: 'data/office_home_dg'
  webroot: 'data/web_office'
  source_domain_x: 'product'
  source_domain_u_1: 'art'
  source_domain_u_2: 'real_world'
  target_domain: 'clipart'

log:
  save_addr: 'log'
  save_name: 'product2clipart'

ratio: 0.4 # a ratio to split samples into clean set and noisy set
